---
# System Updates
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Enable automatic OS updates
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

# SSD Maintenance
- name: Install util-linux for fstrim
  apt:
    name: util-linux
    state: present

- name: Create weekly fstrim cron
  copy:
    dest: /etc/cron.weekly/fstrim
    mode: '0755'
    content: |
      #!/bin/sh
      /sbin/fstrim --all || true
